sudo: required
services:
  - docker

before_install:
  - docker build -t lokesh2yss/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lokesh2yss/react-test npm test

after_success:
  - docker build -t lokesh2yss/multi-client ./client
  - docker build -t lokesh2yss/multi-nginx ./nginx
  - docker build -t lokesh2yss/multi-server ./server
  - docker build -t lokesh2yss/multi-postgres ./postgres
  - docker build -t lokesh2yss/multi-worker ./worker
  - docker build -t lokesh2yss/multi-redis-server ./redis-server
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to dockerhub
  - docker push lokesh2yss/multi-redis-server
  - docker push lokesh2yss/multi-client
  - docker push lokesh2yss/multi-nginx
  - docker push lokesh2yss/multi-server
  - docker push lokesh2yss/multi-postgres
  - docker push lokesh2yss/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: "elasticbeanstalk-us-east-2-763443255229"
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

